services:
  - type: web
    name: leaflink-api
    env: node
    buildCommand: npm install
    startCommand: node server.js
    rootDir: backend
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: CLIENT_URL
        sync: false
      - key: OTP_EXPIRES_MINUTES
        value: 10
      - key: RATE_LIMIT_MAX
        value: 100
      - key: RATE_LIMIT_WINDOW_MS
        value: 900000
